### PR TITLE
Making a better poemgame

### PR DESCRIPTION
**Pull request by Bronya-Rand**
This PR does the following
- Makes an attempt to improve the poem game from Dan's code using Screens than `ui.X` functions
- Makes an attempt to improve the poem game from Dan's python code using Classes and inheritance.
- Adds the ability to add more characters easily using the `Chibi` class (or `ChibiTrans` if you don't need points).
> This still requires some code editing for screens and points however. See the new guide in `Documentation` for more information.
- More efficient poem word storing via dictionaries.

(Elk, if by any chance you read this PR, get some water and a pillow because you might rage at this.)

### CODE REVIEW

**Comment by Elckarow** [comment]
_breathes in... and out_

if it works, then go for it
there are a couple things that i ain't happy with tho

image

-the `exec` part straight up won't work. 
instead of storing the appeals in a list, add a new parameter `name` to the `Chibi` constructor and store the object in a dict with the name as its key. that way you can replace this ugly `exec` with `chibis[ch1_choice[0]].charPointTotal += 5`

-goofy ahh sorting code
`poemwinner[chapter] = max(chibis, key=lambda c: chibis[c].charPointTotal )` works way better (with the dict thing i talked about just before)
plus the code won't work if there are more than 3 appeals

**Comment by Elckarow** [comment]
> plus the code won't work if there are more than 3 appeals

the code you wrote....
_just clarrifying_

**Comment by Pseurae** [comment]
This is a much needed change, and I'll contribute however I can because the vanilla code is just painful to look at
Maybe you could salvage _something_ from this incomplete mess
https://github.com/dokimods/poemgame

**Comment by Elckarow** [comment]
i've already sent this to weiss alsongside the new poem response system
here, if you wanna have a look pseurae

[new_poemgame.zip](https://github.com/GanstaKingofSA/DDLCModTemplate2.0/files/11021566/new_poemgame.zip)

**Pull request merged**
